### ISSUE TITLE
Naming convention and code style

### ISSUE THREAD

**Issue by GildedHonour** [ezl/dailyidea.com#157]
For Python code:

1. The single and double quotes are mixed across the project. I propose that we stick to either one.

2. Some methods use camelCase instead of snake_case. The snake_case is the standard for Python.

**Comment by ezl** [comment]
I agree with this ticket, @GildedHonour 

For #2, I think all python should clearly use `lower_case_underscore_separated` for variables and `CamelCaseFirstWordCapitalized` for classes. 

In general, I am personally lazy with single vs double quotes. I am +0 on modifying the updating the codebase to accommodate, but this seems like a sensible approach: https://stackoverflow.com/questions/56011/single-quotes-vs-double-quotes-in-python

In the past another rule I've used is to use single quotes unless it's a string that may include an apostrophe, then double quotes.

@aldarund do you care about either of these?

**Comment by GildedHonour** [comment]
#1 - Alright. @ezl 

2# -
`camelCase` is used now for the method name in `process_incoming_mail.py` --> 

`def processIncomingMail(parsed_email):`. 

If there're other methods like that one -- I've not stumbled upon them yet.

**Comment by aldarund** [comment]
as for quotes - where do u single quotes? I checked and see that in python double quotes used, maybe i missed something.
In js quotes ensured via eslint for frontend.
2 - ye i too see only that method, just when was switched from js to python did it like this, should be changed to lowercase

**Comment by ezl** [comment]
Personally. I don't care what you guys decide on quotes -- just that you come to an agreement or both agree to not care.

On `ClassNameStyle` vs `variable_name_style` though for python I prefer PEP8 (and what is on this line).

I totally understand what happened regarding the lowerCaseCamelCase method names in the .py though since it sounds like this was adapted from javascript.

Overall, just come to an agreement and move forward with it.

**Comment by GildedHonour** [comment]
I've fixed the method name - https://github.com/ezl/dailyidea.com/pull/159
