### ISSUE TITLE
Onboarding flow not showing up after signup via comment/like/share

### ISSUE THREAD

**Issue by f-prime** [ezl/dailyidea.com#435]
1. Onboarding flow does not show up after signup up through a comment, like, or share.
2. When a new user navigates to the All Ideas page for the first time the flow will show.

**Comment by alisonuxdesign** [comment]
hey @f-prime I'm not sure what to do with this ticket.... do you want me to design screens or just direct the proper flow?

**Comment by ezl** [comment]
@alisonuxdesign can you just do an audit and check out if you think we should have a different onboarding flow or different messaging if a user is "signing up" to the site via a comment/like/share?

specifically, i think this means:

if an unauthenticated user who is NOT a user of the site tries one of these actions, say for example "comment" - then we say "oh hi there, give me your email so i can make sure you're a real person and not just a spammer please".

then we send then the confirmation email. when they click through, they've effectively created an account.

at this point I think it's really important for us to think about what we want the user to experience when they click through the email confirmation. (note, this is also old,because now we're ALSO doing the 4 digit code for mobile devices, so this is another reason this needs an audit).

the ipmortant thing to ask is: "what should we be showing the user now?"

(A) on one hand, they were in the middle of an interaction (like/comment/save) and we just verified their email. so we should probably drop them immediately back into completing the action they wanted to complete. they shouldn't have to take any extra steps or click anything in order to complete it. it should basically just automatically say "great, thanks! we posted that comment, Alison!" or "great thanks for confirming, Alison! your comment is now live!"

(B) right after this is the best opportunity to tell the user all about our site and get them to opt into receiving the best ideas or let them know we're going to send them a reminder every day.

(C) and then we probably want to drop them into browsing or entering their own ideas

so when you audit it, please see if the flows are optimal for all 3 cases:

1. unauthenticated user leaving a comment
2. saving an idea, or 
3. sharing an idea with another friend

re #2 in frankie's old comment - this might no longer make sense now after

**Comment by alisonuxdesign** [comment]
### The modals for these are created and detailed below. 

A. In the case of comment/save/share: If the user is the middle of the interaction, we verify their email and drop them back into the action they wanted to complete and show a toast message that their action was completed. As soon as they click into any other navigation tab (other than Explore) they are brought into the onboarding flow. 


### **Mobile**

![bookmarkUnauthorized_portrait_2](https://user-images.githubusercontent.com/63747360/89443577-b33eb780-d70d-11ea-8bf1-10d585293948.png)
<img width="852" alt="bookmarkUnauthorized_landscape_2" src="https://user-images.githubusercontent.com/63747360/89443581-b5a11180-d70d-11ea-9229-b23387441889.png">
![comments_unauthorizedModal_portrait](https://user-images.githubusercontent.com/63747360/89443599-bafe5c00-d70d-11ea-9234-126296dbfa24.png)
![bookmarkUnauthorized_portrait_2](https://user-images.githubusercontent.com/63747360/89443869-247e6a80-d70e-11ea-8eed-930c7f6bf0ae.png)
![Comment posted](https://user-images.githubusercontent.com/63747360/89444089-6c9d8d00-d70e-11ea-8b30-2d3438fe586a.png)





B. In the specific case of share we should allow users to share their content and then exit out of the modal and continue to browse if they want to continue to be an unauthorized user. The user should not have to be authorized to share content. 

B. In the case of like: we verify their email and then drop them immediately into the onboarding flow as this is such a lesser action that I don’t think this should be too disruptive. 

![Like_portrait_3_unauthorizedConfirm](https://user-images.githubusercontent.com/63747360/89443644-ca7da500-d70d-11ea-870c-90c664a5d252.png)

**Comment by alisonuxdesign** [comment]
Closing this ticket in favor of ticket #506
