### ISSUE TITLE
Consider using a different editor

### ISSUE THREAD

**Issue by ezl** [ezl/dailyidea.com#485]
> Generally trix editor might be not the best option, I usually use tiptap editor, it much more developer friendly and Vue based https://github.com/scrumpy/tiptap maybe we can consider using it, there is Vuetify tiptap package also https://github.com/iliyaZelenko/tiptap-vuetify it will allow to write all the components inside the rich editor in Vue.

reference https://github.com/ezl/dailyidea.com/issues/452#issuecomment-652318335

**Comment by vedmant** [comment]
@ezl @ikosovec Also mentioned about this here #909

**Comment by ikosovec** [comment]
I suggest going with tiptap since @vedmant has experience in it already and from technical perspective he suggest we move forward with it.

**Comment by ezl** [comment]
closing this as it will be resolved by #909

**Comment by vedmant** [comment]
@ezl I'll work on integrating Tiptap in this issue, then in #909 I'll add image resize function.

**Comment by vedmant** [comment]
Todo list:

- [ ] Create a wrapper component for Tiptap, add menu bar according to design
- [ ] Fix content scroll with top/bottom fade
- [ ] Images / attachment uploading, deleting

**Comment by vedmant** [comment]
@ezl Some thoughts about adding / removing images while editing. I think deleting attachment and ctl-z issue have to be rethought. 

Previously ctl-z issue was solved by re-uploading image again after it deleted, but the problem here is that it works only for uploaded images during current editing session, if idea is edited next time, it can't reupload image as it didn't upload it during that editing session.

I think this can be solved different way, instead of deleting attachments immediately when they removed in editor, I'll keep track of removed attachments and only delete them when idea is created / updated, this is firstly more simple and solves issue with ctl-z. 

One issue still can take place is that if someone attached files but abandoned creating idea, this attachments will be uploaded but not linked to any idea. For this probably it should be a routine that checks for abandoned attachments. It will be simpler to implement on new backend. Maybe even attachments first be uploaded with temporary flag before idea created.

@ikosovec Maybe should we move this into separate issue?

**Comment by ikosovec** [comment]
> @ikosovec Maybe should we move this into separate issue?

I have created a new ticket for this - #934
