### ISSUE TITLE
dark mode for emails

### ISSUE THREAD

**Issue by ezl** [ezl/dailyidea.com#496]

**Comment by Watson-B** [comment]
Is this what you were thinking @ezl @alisonuxdesign 

<img width="375" alt="lightCode" src="https://user-images.githubusercontent.com/65913664/88716843-8a4a7100-d0d4-11ea-87a1-be27f052826a.png">
<img width="375" alt="lightMagic" src="https://user-images.githubusercontent.com/65913664/88716847-8ae30780-d0d4-11ea-9a1a-64daff8d366c.png">
<img width="375" alt="darkCode" src="https://user-images.githubusercontent.com/65913664/88716848-8ae30780-d0d4-11ea-8e73-84cfb7089b33.png">
<img width="375" alt="darkMagic" src="https://user-images.githubusercontent.com/65913664/88716850-8b7b9e00-d0d4-11ea-93b4-4e2074429eec.png">
 
Mobile versions for the different login emails



<img width="1136" alt="darkDesktop" src="https://user-images.githubusercontent.com/65913664/88716889-97fff680-d0d4-11ea-88be-0bf1f7122b57.png">

I didn't mockup a dark version for desktop since it's still displaying the light email even when I have dark mode turned on.

**Comment by alisonuxdesign** [comment]
yeah i think this looks good @ezl ?

**Comment by ezl** [comment]
i think this looks good. assigning this to @vedmant since he's done the most email work recently.

@vedmant this ticket is to update the styles so that it renders in dark mode better.

**Comment by vedmant** [comment]
@alisonuxdesign @ezl Not sure how exactly to do this task. There is no proper way to detect dark mode, I found only some hacks that may not work. I can add a setting to use to switch on dark mode, but this also may not work as email client actually changes style of email.

Right now in dark mode email looks almost as in the design, only background is darker. I'm not sure if any changes are needed. @alisonuxdesign From differences right now I spotted only darker background color, a bit different fonts size and different color of "Don't worry..." button, on desktop it's yellow while on mobile it's blue. 

Here how it looks on mobile currently:
![Screenshot_20200811-204702](https://user-images.githubusercontent.com/5052406/89931428-c9b8a780-dc14-11ea-87cc-03a9557ce6b7.jpg)

On desktop email already looks the same, also there is no dark mode in gmail.

**Comment by ezl** [comment]
I see -- this is a valid concern. I think this requires more research. Removing from being currently assigned and putting this back on deck, then will discuss internally for design to assess how we should proceed.

I think one of the avenues for handling dark mode is that designers create assets that render well in both modes.

**Comment by alisonuxdesign** [comment]
Closing This ticket and creating a new one to implement Dark Mode ready emails
