### ISSUE TITLE
Update error messaging style and copy in login flow

### ISSUE THREAD

**Issue by vedmant** [ezl/dailyidea.com#518]
Just spotted most likely a bug https://prnt.sc/ty8i8r in error message (edited) 

@alisonuxdesign

**Comment by alisonuxdesign** [comment]
@vedmant Thanks for finding this and reporting it! 

Let's go ahead and implement all the new verbiage for login error screens since you will be touching it. 

1. Can't find an account: 
![logIn_error_createAccount_portrait](https://user-images.githubusercontent.com/63747360/90035941-0a9dd400-dc88-11ea-9ef5-d9c76d1b52ba.png)

2. Invalid email address: 
![logIn_requiredField_portrait](https://user-images.githubusercontent.com/63747360/90035984-17bac300-dc88-11ea-8a39-1a6553496c27.png)

3. Errors with Entering a code: 
Expired: 
![confirmationEmail](https://user-images.githubusercontent.com/63747360/90036062-2c975680-dc88-11ea-8ced-2de876af2d35.png)
Not Valid: 
![confirmationEmail-1](https://user-images.githubusercontent.com/63747360/90036100-391baf00-dc88-11ea-8b0f-c40004ea1a34.png)


This verbiage will apply to both desktop and mobile so I'm not attaching desktop screens. 

Here is the icon pack: 
[Icons for login .zip](https://github.com/ezl/dailyidea.com/files/5063961/Icons.for.login.zip)

**Comment by ezl** [comment]
Updated ticket name, moved to "in progress" in design pipeline, and assigned to @vedmant in dev pipeline.

Thanks both of y'all.

**Comment by vedmant** [comment]
@ezl @alisonuxdesign 

> Here is the icon pack:

This part is a bit confusing, do you want me also to work on design in this ticket or it's only about error message?

**Comment by alisonuxdesign** [comment]
@vedmant what is your call? I thought that since you were in the codebase for this section that we might as well also push a few design changes but maybe I am mistaken. @danleyb2 is taking care of the buttons but new icons and slight design changes with inserting icons might as well get done now. 

Am I mistaken? Is this hard to implement the new design right now?

**Comment by vedmant** [comment]
@alisonuxdesign The thing with design is that it depends on other pages as well, so this have to be done globally in the scope of one or list of issue that are specifically about design, like replacing and moving close icon to the left on all pages that has it,  adding thick underline to all links on all pages. If I just do this on one page, then someone else will do something similar to another page it's very likely that we will have lots of duplicates of the same styles but a bit different, we'll end up with design mess then. So that's why design tasks have to be separated from other tasks, preferable done by one person and applied to whole site, not just one page.
