### ISSUE TITLE
Database migration tool

### ISSUE THREAD

**Issue by vedmant** [ezl/dailyidea.com#522]
Idea is to create something similar to https://medium.com/@geekrodion/migrations-in-dynamodb-b6c9b1099f31

**Comment by f-prime** [comment]
There seems to be a few DynamoDB ORMs out there (or at least something that tries to get close) would it be possible to use one of those? @ezl has mentioned that at some point we are going to migrate the backend to Django instead because of issues like these.

**Comment by vedmant** [comment]
@f-prime We use one ORM pynamodb, but it doesn't have migrations, do you have any specific examples for migrations and ORM?

**Comment by f-prime** [comment]
I saw that we are using pynamodb but I did not realize that it doesn't have migrations. Doing a bit more research it doesn't seem like many do. There are some other tools.. but nothing that looks that good. 

Yeah, now I am not sure how to do this other than the custom solution that you recommended. It's a bit surprising to me that this problem hasn't been solved properly yet.

**Comment by vedmant** [comment]
@ezl @f-prime Ok, I ended up using this package https://github.com/clarityhub/serverless-dynamodb-migrations#readme still having some errors, solving them.

**Comment by ezl** [comment]
> I saw that we are using pynamodb but I did not realize that it doesn't have migrations. Doing a bit more research it doesn't seem like many do. There are some other tools.. but nothing that looks that good.
> 
> Yeah, now I am not sure how to do this other than the custom solution that you recommended. It's a bit surprising to me that this problem hasn't been solved properly yet.

correct, i intend to migrate to django at some point, but only *IF* I can first drive usage on the existing backend.

Basically, if I can't get users or users don't care about this site, it's not worth a rewrite. So unfortunately for now, that just puts us in the awkward situation of making incremental improvements to something that I *HOPE* will be replaced. However, we can't just "do nothing" either since some improvement is still required to test the thesis.
