### ISSUE TITLE
What should happen on clicking a photo inside an idea?

### ISSUE THREAD

**Issue by ezl** [ezl/dailyidea.com#543]
Current behavior:
Navigates to standalone page for that photo with no way to navigate back

Problem:
User gets stuck

Example:
https://www.dailyidea.com/i/3dgdlr/better-airbnb-chrome-extension

Potential alternatives:
1. Click does nothing. Images are not clickable, they are just embedded in the page and are supporting images for the primary content
2. Lightbox

**Comment by alisonuxdesign** [comment]
**1. To be clear the first alternative happens: when the user clicks or taps an image nothing happens.** 

2. Let's also address What the image looks like inside of the card: 

Currently, when a photo is uploaded it is cut off depending on what size it. See screenshot:
![screenshot picture DI](https://user-images.githubusercontent.com/63747360/93722540-d0f89c80-fb54-11ea-8b93-3c2a383da8cb.jpeg)

We want to auto-size the image so that it ALWAYS fits within the card and it never partially clipped and is displayed above the text. See example: 

![idea_settings_desktop with picture](https://user-images.githubusercontent.com/63747360/93722463-3e57fd80-fb54-11ea-8ca7-4e03fe76723f.png)

![shortIdea_img_portrait](https://user-images.githubusercontent.com/63747360/93722472-5039a080-fb54-11ea-813b-d1965b1fa48e.png)

**Comment by ezl** [comment]
> 1. To be clear the first alternative happens: when the user clicks or taps an image nothing happens.

@alisonuxdesign This isn't my experience. My experience on both mobile and desktop is that the image loads and there's no way out of it except to press back on the browser.

https://monosnap.com/file/9UgWwPeDJben6z2Biez40TZSS3HMAW

Can you confirm what browser / device you are using so I can try to replicate please?

**Comment by ezl** [comment]
killed. replaced.
