### ISSUE TITLE
Handle comment attempts for unauthenticated sessions

### ISSUE THREAD

**Issue by patelravi** [ezl/dailyidea.com#56]
If an *UNAUTHENTICATED* user tries to leave a comment, we should:

## First, before we collect the email:

1. allow the user to type the content, as if they are authenticated (currently we don't even allow them to type in the comment input box).
2. When they press send or enter, instead of immediately posting the comment, add the comment, only visible to them, in a different color, with an indication that the comment is pending. If another person loads this page, this comment should not be visible. Regarding whether we should actually persist this comment or not -- I'll leave it to the developers to decide the appropriate course of action.
3. At the same time, pop up a modal to ask for the user's email to verify their identity. "Before we post this for everyone to see, can you please confirm your email address?" ______

## If the email address belongs to an existing user:

If the email entered in #3 above matches that of an existing user, then we:

1. show a message saying: "Welcome back, <name if available else email>! It looks like you weren't signed in. We just sent you a verification email. Please check your inbox and click on the link and we'll post your comment ASAP."
2. send them a verification link. This should use a different email template used specifically for this purpose. "You left this comment _______ on this idea _______. Press this to finish posting your comment."
3. when they click the verification link, it takes them back to the idea page, and the comment is fully posted. If possible, show some sort of highlight / fade css transition so the comment is highlighted, then the highlight fades away slowly over 3 seconds.
4. Show a success message that says: "Welcome back! Thanks for posting that comment!"

## If the email address does NOT match an existing user:

1. If we don't have that user, NOW ask for the person's name: "OK, thanks! And what can we call you?" (placeholder text: First name).
2. show a message saying: "Thanks! We just sent you an email to confirm that you're a real person :) Please check your inbox then click on the link and we'll post your comment ASAP."
3. Send them a verification link. This should be a variant of the one described above for the case where the email address belongs to an existing user.
4. when they click the verification link, it takes them back to the idea page, and the comment is fully posted. If possible, show some sort of highlight / fade css transition so the comment is highlighted, then the highlight fades away slowly over 3 seconds.
5. Show a modal that says: "Welcome <firstname>, thanks for posting that comment! Feel free to browse for other ideas (link to 'all ideas') or add your own ideas (link to 'create idea')"

Edit:
Adobe XD file link: https://drive.google.com/open?id=1JguqEGCGcAG4i51amot_LIBk7NslRWA-

**Comment by inflameous48** [comment]
@ezl What if instead of waiting for them to comment on something, we blur out the comments already posted by other users and in order for them to see those comments, they have to sign up/log in. I assume the goal here is to grow the user base, that means getting as many emails as possible. 

Personally, I'm not a comment type guy, I very rarely comment on youtube/reddit type platforms but if there was an idea that I'm really curious about, I would want to know what other people think about it, or maybe some type of insight I can get from someone that replied. I think the data on reddit is about 15%-20% of users are commenting and 80%-85% are lurkers.

I think the biggest concern here would be the User Experience, would it be too much to ask for them to sign up in order to check the comment section. I think on traditional platforms, where they have to fill in 5-10 fields to sign up, this would a bit evil. But here, they can signup with only 1/2 fields. The way I see the user flow is:

1.  They arrive on the website, most likely on the homepage and check ideas in the "Browse Other People's Ideas" section.
2. They find an idea they might be interested in or someone shares a link to that idea for them to checkout
3. They read through the idea and on the left we have the comment section with username public and comments blurred out, in the middle of the box we have a button that says "Click here to view comments"
4. Once they click that a pop up appears and asks them for their name/email.
5a. New Users - They have to verify their email, once they click the verify button they get redirected to the page where they tried to view the comments with the comments being unlocked.
5b. Old Users - Welcome back, we sent you an email, click on it to log in/view comments.

I'm not sure if this is the best approach, and it might even be a bit annoying, but this could probably be tested and check the results.

**Comment by GildedHonour** [comment]
I wouldn't blur other user's comments.  I'd make the process the same as at Youtube, for instance: 

on click in the comment box either:
a) redirect them to the login page
b) show login popup

The difference is that first would be login/registration action, then commenting becomes enabled . 

Alternatively - I'd show "login or register in a single click" button instead of the comment box which would work the same way.

**Comment by ezl** [comment]
@GildedHonour 

This task is to execute as outlined in the first comment/description that says "patelravi commented on Oct 31, 2019 • edited by ezl" (I wrote that whole part out).

I deliberately do NOT want them to be asked to login or sign up BEFORE entering the comment. I want them to enter the comment first, then be asked for an email to verify, which sends a verification link and posts the comment

**Comment by GildedHonour** [comment]
@ezl I thought it was an open discussion of how to go about implementing the task.  I'll implement it according to your description then.

**Comment by GildedHonour** [comment]
@ezl I thought it was an open discussion of how to go about implementing the task.  I'll implement it according to your description then.

**Comment by GildedHonour** [comment]
@ezl are you aware that there're many moving parts in your approach?

1) While entering an email, user closes a tab - what will happen to his comment? While a comment can be stored in a cookie, it's not a good place to store there due to its (cookie) limitation size - 4096 Bytes max. A comment may not fit in it. 

2) User may enter his email and go straight away to a new idea, still authenticated, and post a comment there. We'll have to store "idea_id:comment" in cookies. Given still that a comment may well not fit into a cookie.

3) User has entered his email and clicked "send me auth link" and then he realizes he's made a typo. We'll have to post somewhere "re-send auth email" link underneath a comment for such a case.

**Comment by GildedHonour** [comment]
Do you want me still to implement it the originally described way?

**Comment by ezl** [comment]
@GildedHonour it's not obvious to me that cookies are necessary or even a good solution here.

as an alternative:
1. when a user submits a comment, just post it in the DOM for that user. no cookie. this is listed as "pending". if the page is refreshed this would disappear.
2. when the user submits the comment AND provides an email address, DO post to dynamodb to create a comment with status "pending" or something and note the email address. That's when the confirmation email gets sent. upon clicking through the confirmation email, the comment entry is updated and the "pending" flag is removed so it's just a regular comment.

Your "complexity" #2 and 4 are resolved by this IMO and doesn't have the cookie constraints.

>  1. While entering an email in the popup, user closes a tab - what will happen to his comment when he reopens a tab -- will the "login/register" popup pop automatically after a page reloads?

In this case the comment is lost. Basically the same as not completing comment.

> 3. User has entered his email and clicked "send me auth link" and then he realizes he's made a typo. We'll have to append somewhere "re-send auth email" link underneath a comment for such a case.

I'm prepared to make people retype comments if they type the wrong email address.

**Comment by ezl** [comment]
Executed perfectly @aldarund !!!! Thank you!!!
