### ISSUE TITLE
[navbar] style: make post and profile look disabled if not authenticated

### ISSUE THREAD

**Issue by ezl** [ezl/dailyidea.com#676]
Make these be light grey if the user is not authenticated:

<img width="332" alt="Daily Idea 2020-10-31 13-00-16" src="https://user-images.githubusercontent.com/157627/97786404-5bcbae80-1b79-11eb-8ca1-6f7faf56e8bb.png">

If possible, use an existing "disabled" style that we already have globally rather than creating a new one. If one does not exist, create a new one at a global css level and apply it so that we can use it in the future.

**Comment by vedmant** [comment]
@ezl The problem with global disable style is that this top button are custom, they are not reused anywhere else, this means if I create disabled class that will work on this buttons, it will not work on other buttons and will require to extend styles so it can affect any other buttons.

**Comment by ezl** [comment]
@vedmant understood. Given our current needs then, how would you recommend doing it?

(A) we could just create a global css class like `.muted` which is a lighter color, then apply it. For now it will only apply to these links when disabled. It MIGHT not ever be used again

(B) we could just put it in the component with scoped style. if we don't ever use this style in the app again, then this will be the right choice. however, if we do need a lighter style again, then we will probably forget that this style is here, and we'll end up recreating a similar light style somewhere else in the app (not very DRY).

Personally, I don't care. Open to any path. Basically, as long as you know that my goal is that these navbar buttons look a lighter color when the user is not authenticated, I'll leave the implementation up to you.

**Comment by vedmant** [comment]
I done it both ways, added a global class and for icons I had to add code as color is passed as props there. Generally making this DRY will be more complicated since that elements are not reused anywhere else. For better DRY it's good to create some separate dev page where we will have whole list of shared and used on site components like buttons, forms, etc, then we can apply there additional shared styles, add new elements, remove not used. Probably even makes sense to wrap all our shared elements in components.
