### ISSUE TITLE
Create a loading animation

### ISSUE THREAD

**Issue by ezl** [ezl/dailyidea.com#718]
@watson-b remind me to show you customer.io's loading screen

**Comment by Watson-B** [comment]
First pass at a loading screen inspired by customer.io's
### GIF
![loading](https://user-images.githubusercontent.com/65913664/101827658-73397800-3ae5-11eb-8763-570a97f664d2.gif)

### In action
![loading](https://user-images.githubusercontent.com/65913664/101835082-1becd500-3af0-11eb-916b-1b80e55c35a2.gif)

### Uses
So navigating through Daily Idea right now, most pages are loading really quickly for me. The only place where I'm getting a slowdown is on "My Ideas". As an aside, it's the only place where I'm getting a small black loading bar on the website at the top, no other pages have this. Is that intentional?
### Page loads for me on current site
![current](https://user-images.githubusercontent.com/65913664/101836205-cdd8d100-3af1-11eb-822c-3570a984e8ac.gif)

### Wipes between sections
Would you want to do wipes with the loading in between sections? Or just as an intro to the website? Here's a sample of what a wipe in between pages might look like. 
![white-wipe](https://user-images.githubusercontent.com/65913664/101835579-d8df3180-3af0-11eb-8adb-ed2755c2b0b3.gif)

Given how quickly the pages load, using the character load between sections might be a blur that doesn't really register. I tried it with yellow, and thought that worked better. Thoughts?

![yellow-wipe](https://user-images.githubusercontent.com/65913664/101835594-dda3e580-3af0-11eb-89de-14bf77a83eb0.gif)

**Comment by ezl** [comment]
Let's not do the wipes. Let's just do the loading animation. If it loads too fast to see, that's ok. The loading animation is there for the benefit of people when the page ISN'T fast enough.

**Comment by vedmant** [comment]
I added custom loading animation, merged to dev. I also can make it appear with delay to prevent flickering on fast load (or add fade in transition).

**Comment by ikosovec** [comment]
I tested it out and it looks good. I have a suggestion to improve it a bit - let's also add the text "Loading" somewhere along with this animation. Although it looks amazing, it might be confusing a bit for first-time users.

What do you think @Watson-B ?

**Comment by Watson-B** [comment]
@ikosovec 100% agree, should I add that to the loading gif, or is that something we would add below it? Happy to do whatever works best for implementation.

**Comment by ikosovec** [comment]
@vedmant what do you think? What would work better?

**Comment by vedmant** [comment]
@ikosovec I'm ok with both solutions.

@Watson-B Could you make a design for loading animation with a text?

**Comment by Watson-B** [comment]
@vedmant How's this? Let me know if you need me to resize anything.
![loading_bulb](https://user-images.githubusercontent.com/65913664/102642933-4b649880-4113-11eb-9263-9cff1ba1a150.gif)

**Comment by ezl** [comment]
@vedmant is there a reason to prefer the text be part of the image instead of actual text?

if it's actual text, it will allow us to use different text for different instances.

for example: "logging in..." or "loading idea..."

**Comment by vedmant** [comment]
@ezl Oh I see, I meant not loading as a part of gif, but just design of whole loading page (image and text). Look like I just missed it, it was there. Sure test makes sense to add as text.

**Comment by vedmant** [comment]
TODO

- [ ] Add "loading..." text

**Comment by ezl** [comment]
perfect. thanks @vedmant :)

this may be unrelated, but i noticed that when i'm logging in by clicking on an authentication link in email, then the login screen still shows a static light bulb while logging in. can we make it so that screen also shows this loading animation, but with the text "logging in..." ?

**Comment by vedmant** [comment]
@ezl Yes, it has different loading screen, two types of lightbulb, gray while checking login, and it turns yellow when login successful, while it still doing some work.

Let me know if I should replace this with this new loading sceen.

**Comment by ezl** [comment]
@vedmant i'll drop the issue of the separate loading screen from this ticket, since it's already discussed in #807 

for this ticket, this can be considered complete and we can close it once the "loading..." text is added.

**Comment by vedmant** [comment]
Ok, "loading..." text is already added

**Comment by ikosovec** [comment]
Looks good!
