### ISSUE TITLE
When creating a new idea, if I leave the text empty, it says "undefined"

### ISSUE THREAD

**Issue by ikosovec** [ezl/dailyidea.com#728]
I created a new idea and left the description of the idea empty. When it got posted, the body says "undefined":
![image](https://user-images.githubusercontent.com/16639403/99530076-1c86c580-29a1-11eb-99a4-8eedf093494a.png)

Maybe instead of "undefined" it should say something like _"This idea has no description"_ in italics.

**Comment by ezl** [comment]
Agreed. Alternate text for empty ones.

However, this may be a *type* error with submission. What I mean is that when an empty string is submitted by the user, it is being sent as an `undefined` javascript type, which is being stored as a *string* with value "undefined" rather than a null.

@vedmant does this make sense?

**Comment by vedmant** [comment]
@ezl It should not show undefined, it's a bug, I'll check it.

**Comment by ikosovec** [comment]
This is fixed. Empty area now shows as a blank whitespace. It looks weird when there's no text, so maybe we should consider making body text mandatory. I'll open a separate ticket for that.
