### ISSUE TITLE
Reconsider "Close" and position of toast messages

### ISSUE THREAD

**Issue by ikosovec** [ezl/dailyidea.com#730]
![image](https://user-images.githubusercontent.com/16639403/99534019-0d0a7b00-29a7-11eb-94d0-092c70e5138c.png)

There's 2 things about the toast messages that I think we should talk about:
1) The "Close" button
In most cases, the toast message disappears so fast that I don't even have the time to close it. Also, having a "Close" on toasts in an anti-pattern. It's a toast - we know it will disappear in a sec.

2) The positioning
The top right seems somehow off for me. On larger screens (I use a 32"), if I do an action, e.g. "Like" an idea, I have to move my visual focus to the top right of the screen, to see a confirmation that I liked the idea and then go back with my focus to what I was doing before. The visual cue of increasing the "Like" counter on the idea card by 1 should be enough of a confirmation that my action worked. In correlation with point 1, the toast even wants me to close it (as a first time user, I might think it won't disappear otherwise), which is not a great experience.
From my perspective, the usage of the toast component should be in the visual focus of the user as an additional confirmation that their action either succeeded or did not succeed. So I propose to move it to the center and lose the Close button.

What do you think @ezl?

**Comment by ezl** [comment]
Agree. I think this requires design work, but we should standardize how/where the toasts show up and what they look like.

IMO these toasts are too "strong".

@Watson-B thoughts?

**Comment by Watson-B** [comment]
@ezl I agree, I think the toast feels too strong. I also think @ikosovec is right, it seems odd having it so far away from where the action took place. I can work on a design update for this tomorrow.

**Comment by Watson-B** [comment]
@ezl @ikosovec What about something like this? Idea behind it being that it moves vertically from where the user made the action, and like @ikosovec suggested, it cuts the close button and just disappears after a short period ( I have it for 1 sec right now, I think the time for both the reveal and duration shown could be pushed longer though).
![toast_sample](https://user-images.githubusercontent.com/65913664/99730667-b3bb4e00-2a71-11eb-8b3c-30b0edef85e4.gif)

**Comment by ikosovec** [comment]
I simply love this proposal @Watson-B :)

**Comment by ezl** [comment]
I like this too. @Watson-B I'd be interested in seeing one where the success message has a green outline -- could you mock that up too?

**Comment by Watson-B** [comment]
green toast sample
![green_toast](https://user-images.githubusercontent.com/65913664/99858353-38759d00-2b42-11eb-8798-b6bd999b9b0c.gif)

**Comment by Watson-B** [comment]
Sample of the green toast
![green_toast_2](https://user-images.githubusercontent.com/65913664/99858853-4d066500-2b43-11eb-9243-5d6d57dfdf8b.gif)

**Comment by ikosovec** [comment]
I personally think the green is indeed a better solution.

**Comment by ezl** [comment]
i like the green as well. lets not prioritize this for execution yet. lets do a session early next week and review priorities to see where this one sits.

we will do it, but just want to make sure we get functionality/errors done first.

@vedmant in order to execute this, would you need any design files? if so i just want to get them attached to this ticket now, even if we won't execute immediately.

**Comment by vedmant** [comment]
@ezl Yes, I'll need that icons on the toast in svg.

Also I have concert about toast position, I see it's right about the card, but toast doesn't position relative to any elements, it's attached globally. I can position in in the center with the top distance like on design, but on other pages it's likely will cover some elements.

Another issue is with animation, like it pop ups from the card. Since we have global element is's not attached to card, so I can do animation like slide up and fade in but not attached to card position.

If to do this exactly like on design then it have to be a separate toast component, created specifically for idea card and different from all other toasts on the site.

**Comment by ezl** [comment]
@vedmant these are good points regarding toast positioning.

@ikosovec and @Watson-B - I agree with @vedmant and we need to think about how toast messages will render on ALL pages, not just the current one.

Basically since this renders in a specific place on this page, it won't work seamlessly on other pages. The currently deployed toasts are designed to be able to float over the entire page, in the same fixed location regardless of the content.

2 common patterns I see for toast message placement are:
(A) as the current version does it - fixed in one location, floating over the content
(B) from the top, pushing a banner down

@Watson-B any recommendations? (have @vedmant and I communicated the challenges of this toast method clearly?)

**Comment by Watson-B** [comment]
@ezl @vedmant This makes sense. Looking across all of the pages, the only screen space that could consistently house a toast is the bottom of the screen which then brings up the original pain point of the toast being too far from the point of action. I think going with option B, with a toast pushing a banner down would be the better solution. Mocking it up now.

**Comment by Watson-B** [comment]
Since the top nav is consistent across all pages, would it be possible to have it appear below it, pushing other elements down (depicted below)?
<img width="1440" alt="desktop_banner_1" src="https://user-images.githubusercontent.com/65913664/100002012-d2268f80-2d78-11eb-84ab-39eb43c97cea.png">
<img width="1440" alt="desktop_banner_2" src="https://user-images.githubusercontent.com/65913664/100002006-d0f56280-2d78-11eb-9497-46b05b23aa86.png">
<img width="1440" alt="desktop_banner_3" src="https://user-images.githubusercontent.com/65913664/100002010-d2268f80-2d78-11eb-9b45-dbe8696f54ed.png">

Then on mobile doing something like this?
<img width="415" alt="mobile_1" src="https://user-images.githubusercontent.com/65913664/100002315-42351580-2d79-11eb-86eb-0bb28d2c95f0.png">
<img width="415" alt="mobile_2" src="https://user-images.githubusercontent.com/65913664/100002316-42cdac00-2d79-11eb-8d4d-5c3f07c9f77a.png">
<img width="415" alt="mobile_3" src="https://user-images.githubusercontent.com/65913664/100002320-43664280-2d79-11eb-9fb6-f020d443d086.png">

**Comment by vedmant** [comment]
[@Watson-B @ezl There is one issue with pushing whole page down, there are many pages cards fit vertical page height, so if I push whole page down it may either add a scrollbar or bottom part can be cut if to disable scroll.

**Comment by ezl** [comment]
Ah man, @vedmant -- I want to commend you here -- you're really demonstrating your value to me and the team in this thread.

@Watson-B @ikosovec not sure if this is really obvious to you 2, but this is so good it's public praise-worthy.

A lot of engineers would just implement a bad version of a solution. @vedmant is pushing back and explaining the negative side effects before implementation and I believe it's helping us come to a stronger solution.

@vedmant I see you are correct here. The "push the page down" model is pretty common on sites, but the vast majority of sites do NOT have a "fixed height" page that uses card swipers and scrollable lightboxes. So on a typical site, pushing the content down is fine.

In our case, since we DO have a fixed height, it will cause the viewport to go from a non-scolling state (all content contained within the height) to a scrolling state, which would cause a scrollbar to appear then disappear later.

(A) this is probably ok, since it's temporary -- but it's really not intended
(B) an alternative is to have the top banner slide down and just cover up top content.

Personally I vote for (B). It's not ideal, but it's:
* better than introducing (message appears and pushes content down) then removing (message disappears, shortening screen back) scroll
* consistent with the other style of toast message which covers up screen content anyways - and the content it covers is just the header content anyways which isn't important at that time.

Thoughts @Watson-B and @ikosovec ?

**Comment by Watson-B** [comment]
@vedmant great call, I feel like seamless interactions is key to the experience of the platform; so thanks for the foresight, I hadn't thought of that. @ezl I think option B would be the better approach, it still keeps it near the point of action, and will only cover the nav for a brief moment. Mocked what that might look like down below. Since it will be covering nav elements on some screens, is there any merit in adding a 'close' button back in for impatient users?
 

<img width="415" alt="mobile_2" src="https://user-images.githubusercontent.com/65913664/100138090-57c24200-2e42-11eb-88c4-87b3e9b5502e.png">

<img width="1440" alt="desktop_banner_1" src="https://user-images.githubusercontent.com/65913664/100138091-585ad880-2e42-11eb-9ab4-04d436f928b3.png">

<img width="1440" alt="desktop_banner_1-1" src="https://user-images.githubusercontent.com/65913664/100138088-56911500-2e42-11eb-988a-e0548d79745e.png">
<img width="415" alt="mobile_1" src="https://user-images.githubusercontent.com/65913664/100138089-5729ab80-2e42-11eb-9043-99e647f9ef88.png">

**Comment by vedmant** [comment]
@Watson-B Can you attach icons used here in svg?

**Comment by vedmant** [comment]
@ezl @Watson-B I changed snackbar style, about icons in snackbar, I'll then need to put required icons for all actions where we have this notification, here is full list:
<img width="570" alt="Screenshot at Nov 26 16-08-10" src="https://user-images.githubusercontent.com/5052406/100360412-98b48500-3001-11eb-9b5c-471b379f8168.png">

**Comment by Watson-B** [comment]
@vedmant @ezl I'm thinking we can reuse to icons for some of the above actions. If you have other thoughts let me know, and I can create more icons. I'm attaching the SVGs in a zip, and then referencing PNGs in the post

I'm thinking use this general error one <img width="22" alt="error" src="https://user-images.githubusercontent.com/65913664/100489120-4c337d00-30c7-11eb-9bea-c61e93811065.png">
_(labeled 'error' in the zip)_ for:
 "Can't delete comment"
"Can't update idea"
"Can't change idea visibility"
"Something went wrong"
"Can't share idea"
"error"
"Can't update email settings"
"Cannot update profile"
"Error during avatar updating"

Use this save icon 
<img width="16" alt="settings updated" src="https://user-images.githubusercontent.com/65913664/100489169-8735b080-30c7-11eb-9247-f233c28f6008.png">
_(labeled 'settings updated')_ for:
"Idea updated"
"Email Settings Updated"
"Profile Updated"
"Avatar Updated"

Use these icons for idea liked/unliked
<img width="24" alt="like" src="https://user-images.githubusercontent.com/65913664/100489210-c7952e80-30c7-11eb-9e20-e9f2bb3bec82.png">
<img width="24" alt="unlike" src="https://user-images.githubusercontent.com/65913664/100489211-c82dc500-30c7-11eb-9a11-6dafdd2b47d0.png">

Use these icons for saved/unsaved
<img width="29" alt="idea saved" src="https://user-images.githubusercontent.com/65913664/100489217-cfed6980-30c7-11eb-9a46-7387f4843d68.png">
<img width="21" alt="idea unsaved" src="https://user-images.githubusercontent.com/65913664/100489218-d0860000-30c7-11eb-8a23-665429d1e29a.png">

Use this icon for "idea shared"
<img width="24" alt="shared" src="https://user-images.githubusercontent.com/65913664/100489222-db409500-30c7-11eb-9b2b-958d91bcfe62.png">

Use this icon for "Idea Deleted"
<img width="23" alt="deleted" src="https://user-images.githubusercontent.com/65913664/100489229-ebf10b00-30c7-11eb-9f9d-d0a8364f0146.png">

Use these icons  <img width="16" alt="private" src="https://user-images.githubusercontent.com/65913664/100489244-01fecb80-30c8-11eb-8fbb-13eb51df4470.png">  <img width="16" alt="public" src="https://user-images.githubusercontent.com/65913664/100489245-01fecb80-30c8-11eb-8001-a4a738d98107.png">  for the visibility change _(labeled public/private)_

Using this icon for "link copied"
<img width="16" alt="copied" src="https://user-images.githubusercontent.com/65913664/100489281-3a060e80-30c8-11eb-8de2-25ecac656407.png">

and using this icon for a general success one
<img width="26" alt="success" src="https://user-images.githubusercontent.com/65913664/100489314-615cdb80-30c8-11eb-9c60-fa3d8bf59673.png">
 


[icons.zip](https://github.com/ezl/dailyidea.com/files/5609835/icons.zip)

**Comment by ezl** [comment]
These all look great.

**Comment by ikosovec** [comment]
Took me a while to test all of these out but I think they're great. This can be pushed to prod.

**Comment by vedmant** [comment]
@ezl @ikosovec What about icons, I didn't add them.

**Comment by ikosovec** [comment]
I made a hasty comment and completely forgot about the icons, sorry @vedmant. 
The toast looks and works great, but let's also add the icon as well. :)
