### ISSUE TITLE
Clicking on "Explore" the first time messes up the page title

### ISSUE THREAD

**Issue by ikosovec** [ezl/dailyidea.com#745]
These are the steps:

- I get to dailyidea.com
- I click on "Explore"
- The page title is the same as the title of the first card. The issue here is that, when you do this for the first time, an "onboarding" card is shown, not the first card. Screenshot:
![image](https://user-images.githubusercontent.com/16639403/100253045-ec12ce80-2f40-11eb-9f1b-52e342775955.png)

If I reaload the site (or close and open it again), the onboarding card will not show and the first card will show - the title will be matching then. 

The title when the onboarding card is shown should be something like "Welcome To Daily Idea!" - the same as the card title.

**Comment by vedmant** [comment]
@ezl Could you confirm if this should be fixed, title represents url and that idea that underneath, explainer card is temporary first time layover.

**Comment by ezl** [comment]
@vedmant - please hold on this

@vedmant and @ikosovec  i agree with @ikosovec that there is a bug here, but I'm not sure what the solution is.

The problem, as I see it, is that it is impossible to see the first card on your first time.

To test this, load an incognito or new browser without any cookies, load daily idea, go to explore.

the browser will show the "welcome" card, as @ikosovec has stated, but whatever the url is will be the FIRST idea.

Now, as far as I can tell, it's not possible to actually see this first card.
(A) viewing the previous idea will show an "already at beginning" message
(B) viewing the next idea shows the second idea

From what I can tell, there isn't a reasonable way for the user to view the first idea (the one reflected in the URL).

So, some possible options:
1. like @ikosovec said, treat the welcome as it's OWN card, with it's own URL (not the first idea url), and by swiping to the next page, it GOES to the first card. Implementation wise, I'm not sure how/if this is reasonable.
2. another option -- treat the welcome as a lightbox that hovers over the first card, and change the INTERACTION to "close" the welcome message. i.e. instead of left/right (i.e. instead of treating it like a card), make it look like a lightbox where the user presses an "x" (upper right) or there's a button on the welcome card that says "ok!" or "start browsing ideas" or something like that,

cc: @Watson-B

**Comment by ikosovec** [comment]
I agree with both options, but I'm leaning towards option 1.

**Comment by vedmant** [comment]
@ezl I think option 2 makes more sense, it's only rendered in browser, I think it's ok to keep is as a card just as is. Option 1 will take more time to implement but doesn't change much, except for the url and title, but why do we even need this as a separate page.

**Comment by ikosovec** [comment]
If the option 2 is a quicker option from a technical perspective, I would then support your opinion here, @vedmant and change my opinion to option 2 as well. :)

**Comment by Watson-B** [comment]
I think both make sense, and don't have a strong preference for one over the other. Did a quick mock of what the lightbox might look like.
<img width="1440" alt="welcome_lightbox" src="https://user-images.githubusercontent.com/65913664/100676464-d07f3d80-331d-11eb-836b-c71d3101ea0d.png">


The only argument I can think of for option 1 over option 2 is that it starts training the user to swipe, but they would end up doing that anyways as they explore, so I think the upside is minimal and if option 2 is easier to implement then I'm all for that.

**Comment by Watson-B** [comment]
@ikosovec Just wanted to check and see if this can marked as done? Tested by clicking explore on the beta site and since we've changed how we treat the explainer, this doesn't seem like it's an issue anymore, correct?

**Comment by ikosovec** [comment]
That is correct. I'm closing this.
