### ISSUE TITLE
Hide share icon on private ideas

### ISSUE THREAD

**Issue by vedmant** [ezl/dailyidea.com#775]
They can't be shared

**Comment by vedmant** [comment]
@ikosovec @ezl  It doesn't show error when trying to share private idea, but doesn't share it, I think removing icon makes more sense.

**Comment by ikosovec** [comment]
That makes sense to me. What about the UX perspective, what do you think @Watson-B ?

**Comment by Watson-B** [comment]
@ikosovec I think hiding it all together might be confusing, what about using a disabled gray state, or even doing a disabled share icon?
<img width="24" alt="disabled" src="https://user-images.githubusercontent.com/65913664/101676079-8548e700-3a0f-11eb-99bf-a18232a3d45f.png">
I think making it clear that they can't share due to an idea being private is an important distinction to make.

**Comment by vedmant** [comment]
@Watson-B Sure, disabled share icon is good idea, can you share SVG icon?

**Comment by Watson-B** [comment]
Here you are @vedmant [disabled share.zip](https://github.com/ezl/dailyidea.com/files/5674737/disabled.share.zip)

**Comment by ikosovec** [comment]
Can we add a tooltip "Private ideas can't be shared" when hovering over the icon? This might be confusing. I'll explain more in #794

**Comment by vedmant** [comment]
Ok, added tooltip

**Comment by ikosovec** [comment]
Looks good!
