### ISSUE TITLE
Super long words in comments stretch the comment area

### ISSUE THREAD

**Issue by ikosovec** [ezl/dailyidea.com#779]
Steps:
- Open a random idea on "Explore"
- Post a really long word in a comment, like "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbaaaaaaaaaaaaaaaaaaaaaacccccccccc"
- The comment area will strech. I propose that the word gets separated with a dash. Is this possible?

Here's a video: https://monosnap.com/file/aPVOakqjRNbmkt1gnJcg7psIyDmIxT

**Comment by ikosovec** [comment]
Although it's implemented nicely, I'm not too happy how it looks from a visual perspective. 
I'd kindly ask @Watson-B for help regarding this. You can see how it looks like on this one: https://beta.dailyidea.com/i/ax83di/test-idea-again

**Comment by ikosovec** [comment]
There's also one more thing that popped on my mind now - maybe we want users to enter newlines in comments? A large comment might look cluttered. What do you guys think?

**Comment by Watson-B** [comment]
@ikosovec I agree, I noticed it end of last week, it feels odd if you're writing a long response to someone, since you're limited to viewing such a small portion of the comment you're leaving. I'll work on this today.

**Comment by Watson-B** [comment]
@ikosovec I agree, I think the link break in the word works now, but I'm not 100% happy with how it looks visually either. When writing a long comment or reading a long comment it's crammed. It makes it particularly hard to proof a comment before submitting, which I'm assuming will impede people's ability to discuss ideas (maybe I'm overthinking that) A few different ideas come to mind on how to handle it. 

In regards to newlines in comments, I think it depends on how people are using comments. If they end up being a place where people are having in depth conversations about ideas, then allowing them more control over formatting and breaking up responses makes sense. If comments end up being short, then it feels unnecessary. Are there any technical reasons to not add line breaks?

I added these the ideas to the click-through I was working on to see how they feel. It can be seen [here ](https://www.figma.com/proto/VTAWAu8G6jtzpWYulfpw9m/Daily-Idea?node-id=25%3A10&viewport=2788%2C-1519%2C0.4245905578136444&scaling=min-zoom) if you want to click through instead of looking at the images. For some reason, Figma's prototyping can be a bit buggy sometimes, so certain interactions might not always trigger. To get started, just click on the loading screen.

First idea: Since the version you linked, drops the comments from the side of the card and allows the card to be scrolled, this take expands the idea to take up the full card. When the user clicks on the comment bubble rather than open the idea with the side tab of the comments, it could open just the comments with the option to post a comment down below. 

(in linked prototype to view this go "My Ideas" > (click) "Cross-play any game" card

<img width="1480" alt="full-bleed-idea" src="https://user-images.githubusercontent.com/65913664/101704139-f3ee6a80-3a38-11eb-8fa3-52ce2e4aab86.png">
<img width="1480" alt="lightbox-comments" src="https://user-images.githubusercontent.com/65913664/101704142-f5b82e00-3a38-11eb-882b-4f92ae3c9a2a.png">

Second idea: Inspired by the pattern Twitter uses on mobile, this has a comment field that grows vertically as the user types a comment, and a "fullscreen" icon to allow the user to expand the comment section.

(in linked prototype (click) through welcome cards > (click) "fullscreen" icon and/or "Join the conversation")

<img width="1480" alt="idea" src="https://user-images.githubusercontent.com/65913664/101704487-b50ce480-3a39-11eb-9d4b-64ac239b239f.png">
<img width="1480" alt="idea-1" src="https://user-images.githubusercontent.com/65913664/101704489-b63e1180-3a39-11eb-8812-99a3a4515aaf.png">

Third Idea: This is the weakest take I think, it makes the comment sidebar wider to help legibility, and marries the two ideas above. When the user goes to post a comment, it opens in a lightbox and allows them more formatting options. 

(in linked prototype (click) "post" > (click) "Add a title" > (click) "Post" > (click) "Join the conversation
<img width="1480" alt="idea posted" src="https://user-images.githubusercontent.com/65913664/101704924-aecb3800-3a3a-11eb-86c8-fcb5f5fb92d3.png">
<img width="1480" alt="idea-2" src="https://user-images.githubusercontent.com/65913664/101704841-762b5e80-3a3a-11eb-9b97-3d00237d0d5d.png">

**Comment by Watson-B** [comment]
@ezl What do you think? Does one make more sense than the other?

**Comment by ezl** [comment]
Of the 3 ideas, I prefer the 1st (no split screen, separate lightbox for comments).

I'm not sure that I'm ready to execute any of these though.

Thoughts:

(A) I don't think that any of these solutions will "fix" the problem of horizontal scroll if a user enters a VERY long word like

fffahdlkfhawelfhliawuyhaiwdugyfonaeiuwrhoerutyoirewuaytaoiwejatyoweijtxyaoiweycfgoawfycoaiwecyofiawuefioaewyfoiauwemfyoiawemyfoicawefiocuaewyofiuawecyfoiauwecfyoacwfawecfaewcfawefawcefaewfcaewcfaewfaewcfaewcfaeaewcfaewfcaewfaw

This issue is a question of how we fix the `line-break` CSS attribute ([link](https://developer.mozilla.org/en-US/docs/Web/CSS/line-break)).

Basically, for a container of ANY size (narrow like the current implementation, wide like proposal 1, or variable like proposal 2), if an UNBROKEN string (sequence of characters) with no "whitespace" characters (space, tab, etc) happens, then it will force a horizontal scroll in some CSS `line-break` settings.

So my first proposal is that we create a SEPARATE ticket to fix this so that words that are too long are forced to break. This can be done with a single CSS edit, I believe (@vedmant can you confirm?)

(B) I think it's important to separate the *DISPLAY* of comments from the *ENTRY* of comments. Proposal 2 by @Watson-B is, I believe, focused on ENTRY. Variable height / expanding as the user types more is a nice UX innovation for when a user is ENTERING a comment -- but doesn't solve the issue of stretching the comment area. For what it's worth, I do think that the proposal is an improvement over what we currently have for comment entry, but I want to separate the issues for now (will explain why next).

(C) @Watson-B - I really love your assessment here:

```
In regards to newlines in comments, I think it depends on how people are using comments. If they end up being a place where people are having in depth conversations about ideas, then allowing them more control over formatting and breaking up responses makes sense. If comments end up being short, then it feels unnecessary.

Are there any technical reasons to not add line breaks?
```

I think you've hit the nail on the head. The right UX implementation is dependent on how users will use it (or how we want them to. 

As such, since currently we have NO users, I'd like to kick the UX entry question down the road to when we actually DO have users.

What I'm trying to avoid is redoing the comment section right now before we have any user feedback.

Therefor my proposal for now is that we just force line breaks for long comments in the current UX, but force the words to cascade if they overflow.

**Comment by vedmant** [comment]
Ok, I edited css property. Not sure if I need to do anything else in scope of this issue, moving to merged.
