### ISSUE TITLE
Context for "Top" on "Explore"

### ISSUE THREAD

**Issue by Watson-B** [ezl/dailyidea.com#790]

**Comment by Watson-B** [comment]
When a user selects Top from the sub-nav, it's showing what I'm assuming is top of all-time, but it's unclear. What do you think about adding a dropdown to allow the user to set context/timeframe for Top? 
<img width="1162" alt="top" src="https://user-images.githubusercontent.com/65913664/101838843-2d38e000-3af6-11eb-9198-46d408af03b8.png">

I'm thinking something along the lines of how Reddit has their top dropdown

![image](https://user-images.githubusercontent.com/65913664/101838873-3a55cf00-3af6-11eb-9a7c-9c75e4bdc22a.png)

**Comment by Watson-B** [comment]
@ezl thoughts on this? Does this make more sense to save for v2?

**Comment by ezl** [comment]
@Watson-B you read my mind about needing this. Let's just implement.

**Comment by ikosovec** [comment]
Do we need any design on this part or can we reuse already existing components?

**Comment by Watson-B** [comment]
I modified the post edit dropdown a bit, would this work @ikosovec? 
<img width="1480" alt="top-2" src="https://user-images.githubusercontent.com/65913664/102256657-7e631e00-3ec0-11eb-9b89-f1efd6073d4c.png">
<img width="1480" alt="top-1" src="https://user-images.githubusercontent.com/65913664/102256651-7d31f100-3ec0-11eb-8527-0d59846eab47.png">

**Comment by vedmant** [comment]
@Watson-B @ezl I think it makes sense to show only when Top is selected?

**Comment by Watson-B** [comment]
@vedmant Agreed, no need to show it when it isn't relevant to what the user is looking at.

**Comment by vedmant** [comment]
@ezl  This will be complicated to do on backend, I don't see a way to do this with appsync mapping template as current function uses. So I'll need to move it to python function and basically do all this in python manually.

I'm not that good with DynamoDB, so I guess following algorithm:

1. Select ideas ids from likes table for specific date range, then group them locally, and sort by max items in the group (I guess this may fail if there are some large number of likes for the period).
2. Select needed ideas using ids (also check for visibility). 
3. Paginate manually

@aldarund You know more about DynamoDB, what do you thing about this? 
Maybe you know the way to do basically this simple thing in SQL but with DynamoDB (example from other project, just posts instead of ideas):
```
select *, count(likes.id) as likes_cnt
from posts
left join likes on likes.post_id = posts.id
where likes.created_at > '2020-12-01 00:00:00'
group by posts.id
order by likes_cnt desc
limit 10
```

Also maybe we can try Hive https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/EMRforDynamoDB.html ? It allows to query DynamoDB in SQL-like language.

**Comment by ezl** [comment]
@vedmant let's hold off on this for now.

Reasons:
1. more complicated to execute than originally thought, but doesn't have a large user impact and value
2. trying to touch the database and backend as little as possible until future rewrite to django - so possible that we can wait on this until the future.

@ikosovec just tagging you here so you understand why i'm deprioritizing this and removing it from immediate implementation

i'm moving this ticket back to Icebox.

**Comment by vedmant** [comment]
@ikosovec I think this makes sense to do only after backend rewrite, this is mostly backend work.

**Comment by ezl** [comment]
Agreed with @vedmant -- this will be after a backend rewrite (soon).

This will be rolled into a future design card, so for now I'm moving this out of the Dev kanban completely and into Design since it is now a topic of discussion for @Watson-B  and I

**Comment by Watson-B** [comment]
Updated approach covered in #954
