### ISSUE TITLE
Unsaving an idea on profile

### ISSUE THREAD

**Issue by Watson-B** [ezl/dailyidea.com#867]
I think I found a bug/potential point of confusion on the "Saved Ideas" tab of the "Profile Page". 

1. If I click the bookmark icon to unsave an idea, I get the banner saying it is unsaved and the idea stays on the page now with the unfilled icon.

![unsave-1](https://user-images.githubusercontent.com/65913664/105251405-4474df80-5b30-11eb-880d-7c69beefde9b.png)

2. When I refresh the page, the idea still shows up, but it shows that it has been unliked instead of unsaved.

![unsave-2](https://user-images.githubusercontent.com/65913664/105251418-4c348400-5b30-11eb-9558-642cbf7b5ae4.png)

3. If I click unsave again and refresh then it disappears.

![unsave-3](https://user-images.githubusercontent.com/65913664/105251421-4e96de00-5b30-11eb-8428-9906514b393c.png)

**Comment by Watson-B** [comment]
Had it happen twice, and now it's not happening. Can anyone replicate this? @vedmant @ikosovec 

First time, I went to settings and then back to saved ideas, and the second time just refreshed. Just tried both again and it is working as intended.

**Comment by ikosovec** [comment]
@Watson-B did this happen on the beta or on the production website?

**Comment by ezl** [comment]
@ikosovec -- in general, the best place to check bugs is beta -- beta is the most recent code. if it's in prod but not in beta, then it means it'll get fixed in the next release.

I haven't checked this, but overall, I can imagine this happening -- originally, we had like AND save as separate functions. Then we merged them into just a single thing. Then we separated them again.

Therefore it's very likely we just are updating the wrong attribute when we push the button in the web site.

**Comment by Watson-B** [comment]
@ikosovec The prod site, but I just had it happen on the beta site too. When I refresh on the beta site though then it disappears, so I only get the first half of the issue.
![image](https://user-images.githubusercontent.com/65913664/105747517-b6b13f80-5ef5-11eb-903f-82a2745fd01f.png)

**Comment by ikosovec** [comment]
Thanks for the info @Watson-B - moved it to prioritize development
