### ISSUE TITLE
Remove dialogues and use banners instead

### ISSUE THREAD

**Issue by ikosovec** [ezl/dailyidea.com#878]
Original discussion here: #871 

I think the title is self explanatory. Please let me know if you need more help @vedmant! :)

**Comment by vedmant** [comment]
- [ ] Idea Liked!
- [ ] HOORAY! First Idea Liked!
- [ ] Idea Saved!
- [ ] HOORAY! First Idea Saved!
- [ ] Comment Posted!
- [ ] HOORAY! First Comment Posted!


- [ ] WELCOME! Use your arrow keys to browse ideas. ???
- [ ] WELCOME User Name! Use your arrow keys to browse ideas. ???

**Comment by vedmant** [comment]
@Watson-B I see also new notifications like "WELCOME! Use your arrow keys to browse ideas. " and "WELCOME User Name! Use your arrow keys to browse ideas. " when they should appear and in what case "User Name" should be added?

**Comment by Watson-B** [comment]
@vedmant as reference the screenshots I'm linking here are from the [Messaging Tree](https://www.figma.com/file/VTAWAu8G6jtzpWYulfpw9m/Daily-Idea?node-id=202%3A1292).

The "WELCOME! Use your arrow keys to browse ideas" & "WELCOME User Name! Use your arrow keys to browse ideas" texts are displayed on the banners after the action banner shows the confirmation of the initial intended action (idea liked, idea saved, comment posted, etc). The thought process here was to account for instances where a user would land directly on an idea without going through the explainer cards first, and take an action. This way, they would be given direction on how to navigate without having to show them the explainer cards or interrupt them with a modal. 
![image](https://user-images.githubusercontent.com/65913664/107980431-1ccd3780-6f75-11eb-9497-d65c7ef16622.png)

However, in two flows, when a new user completes the on boarding flow after clicking either share or My Ideas, it will display without first displaying the intended action confirmation banner.

**Comment by vedmant** [comment]
@Watson-B 

> texts are displayed on the banners after the action banner shows the confirmation of the initial intended action (idea liked, idea saved, comment posted, etc).

So just add another notification with this text every time after (idea liked, idea saved, comment posted, etc) notifications are displayed?

> The thought process here was to account for instances where a user would land directly on an idea without going through the explainer cards first, and take an action. This way, they would be given direction on how to navigate without having to show them the explainer cards or interrupt them with a modal.

Ok, we previously actually had an explainer card for first time users, then we removed it and added to home page. So now we add a notification instead? Also then it means this notifications should show every time user opens Explore page?

**Comment by Watson-B** [comment]
@vedmant Let me sync up with @ezl on this.
My thoughts currently though: Is there a way to structure it so that it doesn't display every time after the action notification is displayed? Since most actions require the user to be logged in, can we base showing the second set of text on if it is the first action taken since logging in? If a user is liking multiple posts, having a banner at the top welcoming them repeatedly and giving instructions every time isn't the best experience. Ideally, we would only show the instructions the first time a user is taking an action. Once they've taken an action multiple times, I think we can assume that they are familiar with navigating the platform.

For the second question, are you asking if we are going to show the banner instead of the card at the start of explore?

**Comment by ezl** [comment]
@Watson-B and @vedmant I have read your comments and I think the questions make sense and require us to think a bit more about it.

@vedmant -- you are correct, we previously had an explainer card, but we changed that from being the FIRST card when viewing ideas to being the LAST card in the "homepage" sequence. The consequence of this is that:

(A) in the "user visits home page and goes to view ideas" case, the user has the SAME experience, but it's just "grouped" differently. i.e.

homepage[1 + 2+ 3] + [explainer card] + [ideas ...] ==>
homepage[1 + 2+ 3 + explainer card] + [ideas ...]

(B) in the case that the user came to view ideas through ANOTHER funnel (for example, an existing user on a new browser wants to leave a comment), then it does NOT hijack the intended action by showing the explainer card (this is a benefit. however, this means that through all the NON-HOMEPAGE paths, users never see the instructions. Therefore, Watson's idea was to add the instructions in via the message in a non-obtrusive way.

Overall, I agree that we can move the question of when/where/display criteria for the "welcome + instructions" banner to another issue: https://github.com/ezl/dailyidea.com/issues/896

If the other banners are implemented then we can close this one, @ikosovec.

**Comment by vedmant** [comment]
@ezl Ok, then I move this to Merged and work on #896 when it's ready for me to implement.

**Comment by Watson-B** [comment]
@vedmant after talking with Eric yesterday, I updated the page [in Figma](https://www.figma.com/file/VTAWAu8G6jtzpWYulfpw9m/Daily-Idea?node-id=202%3A1292) to include the different flows and banners.
For instances where it is the first time a user is taking a specific action (like, save, share) on their account we will show the follow up banner. Demo of how I'm envisioning the transition, I don't think it needs to be anything too extra. The key is to give the first message extra screen time since it will appear at the same time as the confetti. In total, this one takes 4.5 secs for both messages. @ezl thoughts on the timing?
![toast-2](https://user-images.githubusercontent.com/65913664/108918753-b97f7d00-75e6-11eb-8955-40a68ecda6a8.gif)

There is also a simplified tree to the left of the updated screen tree, since it's a bit tricky to read the screen tree at a glance. Note: The secondary message for an unauthorized user commenting is grayed out. I haven't had a chance to discuss with @ezl and @ikosovec the desktop idea view & comment location updates yet, so I'm unsure of how that will impact the second banner message.
![image](https://user-images.githubusercontent.com/65913664/108918913-fea3af00-75e6-11eb-9281-b7f7369aeb80.png)
