### ISSUE TITLE
Update global loader to include appropriate message for the action (like / save / comment)

### ISSUE THREAD

**Issue by ikosovec** [ezl/dailyidea.com#879]
Original discussion here: #871

**Comment by vedmant** [comment]
- [ ] liking the idea...
- [ ] saving idea...
- [ ] posting your comment...
- [ ] going to Post...
- [ ] going to My Ideas...

**Comment by vedmant** [comment]
@ikosovec @ezl 

> going to My Ideas...

I see this section in Figma is also quite different from what we have now, there is new "Oops you’re not logged in." screen (on actual my ideas page? I see menu is active). 

Also the same auth flow applied there, but currently it just redirects on separate login page. So before I can implement loading message "going to My Ideas..." I'll need to redo how authentication on my ideas page works. I think it needs a separate issue.

**Comment by ezl** [comment]
ok, sounds good, @vedmant. I see this issue is already merged, so we dont need to discuss the remaining "going to my ideas" issue.

@ikosovec can you ticket that separately please? After it's ticketed, please tag me. I'd like to discuss with @vedmant about what rewriting is required before we proceed on it. It's possible that we won't execute this if it's a significant change.

**Comment by ikosovec** [comment]
Separate ticket: #894
