### ISSUE TITLE
What should happen if user cancels entering email address to post new idea?

### ISSUE THREAD

**Issue by ezl** [ezl/dailyidea.com#897]
to replicate situation:
1. go to daily idea, not logged in
2. click on "post" - should be directed to enter email
3. try to cancel.

behavior i see:
(A) nothing happens if pressing cancel
(B) nothing happens if pressing "X" in upper right
(C) if clicking outside modal, goes to a blank page

objective:
define the intended behavior from this screen in the "sad paths"

<img width="971" alt="Xnip2021-02-22_14-12-00" src="https://user-images.githubusercontent.com/157627/108764399-29730200-7518-11eb-96dc-e401c3415eba.png">

**Comment by Watson-B** [comment]
@ezl I looked through how we are using all of our modals, "x", and cancel; and I propose the following change:
![image](https://user-images.githubusercontent.com/65913664/109065044-083d1d80-76a0-11eb-98e7-985850bdb6cd.png)
When the user clicks "Go Back" they are taken back to the Explore page, since that is the only path they have available when unauthorized. Everywhere else on the platform we are training the user that hitting "x" or clicking outside of the modal closes it and shows the content behind (prompt after attempting to like, to save, to comment, to share). For Post and My Idea, there is never really anything behind the modal, since they will be taken to a new tab of DI after clicking the link in their email.

**Comment by ezl** [comment]
agreed with your proposal.

lets not do the alternate proposal though:

> We could also use the same pattern that is used on My Ideas, and have them click to pop open the modal, but that requires an extra click.

**Comment by Watson-B** [comment]
@ikosovec we got the go ahead to move forward with this.
