### ISSUE TITLE
when editing idea text, left/right is paginating ideas

### ISSUE THREAD

**Issue by ezl** [ezl/dailyidea.com#906]
# Problem

When entering "edit an idea" from idea scrolling ("explore mode") left/right keypress is still causing the idea card below it to swipe left/right (and the idea url is changing).

# To Replicate

You must go to "explore ideas" then find an idea that you have permission to edit, then edit it. It does NOT occur, if you enter the idea edit mode from your own profile (this is a separate issue, which will be solved in the future when we completely change the edit interface so it's not a "hovering" card we are editing).

--

(A) this will probably be fixed when we update the edit styles completely, so shouldn't spend too much time on it.
(B) however, if temporarily we can easily just make the keyboard stop listening to left/right keybindings for swiping ideas, that would be great.

if it's a small-ish task to disallow swiping ideas with left/right WHILE editing (+/- 1 hr), execute now.
if it's a big task though, discuss with @ezl before executing.

**Comment by vedmant** [comment]
@ezl This is a bit complicated, I already stoped left, right keys propagation, but it only works when some editable field is in the focus. Otherwise left, right keys events are fired only on top window level. So to prevent this I'll need to add a global switch to vuex to switch off/on swiper. It's not hard to do, but will require additional time and I'm not sure if it's necessary as left, right when editing doesn't slide cards.

**Comment by ikosovec** [comment]
I guess we can then deprioritize this ticket and close it? Since the logic and layout will change in #916
