### ISSUE TITLE
Update default "unauthorized" page

### ISSUE THREAD

**Issue by ezl** [ezl/dailyidea.com#927]
## Problem

currently we have this in production
<img width="534" alt="image" src="https://user-images.githubusercontent.com/157627/111187986-8cd5da00-8582-11eb-8409-7df98ba51e66.png">

This style doesn't seem consistent with our other images.

## How to replicate

one way to access this page is to go to dailyidea.com while NOT authenticated, then click on "my ideas" in the top nav. in general you will see this page if you try to access ANY page you don't have permission for or are required to be logged in for.

## Requested solution

@Watson-B do we have an updated page for a generic "you need to log in to do that"? If not, can you create one? Minimally, we can just update the image if it doesn't already exist. Can you upload and attach to this ticket please?

(This ticket was created as an outcome of the discussion in https://github.com/ezl/dailyidea.com/issues/894)

**Comment by Watson-B** [comment]
@ezl How about this? That way it keeps the pattern the same as the unauthenticated My Ideas page, but uses generic copy. I'm happy to do a custom illustration for this, but I felt like this one fit. 
<img width="1480" alt="generic" src="https://user-images.githubusercontent.com/65913664/111396995-7eb8b400-867d-11eb-8445-8dfca41b48ee.png">

<img width="130" alt="lightbulb-unlock" src="https://user-images.githubusercontent.com/65913664/111397027-909a5700-867d-11eb-8d12-f20bb7b89b36.png">

**Comment by ikosovec** [comment]
> * can we make the lighbulb character be crying? it is sad that it can't get in
> *

Are we sure we want that?
From a psychological perspective (which is part of my expertise), crying is an overwhelmingly negative emotion. Something that's so negative that it takes over a physical form. It's not like anger, which sometimes can be hidden - crying usually represents something very bad.

When trying to reach out to users' emotions, it's usually like this:
- Make a positive emotion when trying to use the app
- Make a negative emotion when they're already inside, but they abandon a certain funnel. For example if they drop during checkout, or a Duolingo example: if you don't use the app for a few days, it sends you a push notification "Duo is sad" - Duo is their mascot, a green bird, and it is sad because you stopped using the app.
BUT in that case you're already a user. You're trying to raise retention, you're not trying to get new users. If they get a negative emotion while they're signing up, that's not a pattern commonly used - so I would suggest we go in a more positive direction.

For example:
- You're only a few clicks away of being an idea master 
- You're only 10 seconds away from joining a community of brilliant thinkers/innovators
- You're only 1 step away from....

**Comment by ezl** [comment]
@ikosovec interesting perspective. for me, the crying emoji is kind of funny. but everyone has different preferencs and i don't others to feel negatively about DI.

@Watson-B do you have a perspective on this?

**Comment by Watson-B** [comment]
@ezl While I don't see the crying emoji as a genuinely sad emotion (I feel like I end up using it when I'm joking) I agree with @ikosovec that I don't think we should use something that could be perceived as a negative emotion. I'll make the edits you suggest, but I'll also go back to the drawing board and see if I can sketch something out that is bespoke for this page, and captures the feel of wanting to get in.

**Comment by Watson-B** [comment]
Updated illustration for this card
<img width="1480" alt="card" src="https://user-images.githubusercontent.com/65913664/112670061-ab0ec600-8e1d-11eb-8f93-55e8f67f979c.png">
<img width="65" alt="illustration" src="https://user-images.githubusercontent.com/65913664/112670064-aba75c80-8e1d-11eb-9b1e-c8ab64bc4ff1.png">

**Comment by vedmant** [comment]
Pushed to dev directly by mistake.

**Comment by ezl** [comment]
:) no problem.
