### ISSUE TITLE
Tiptap editor bugs and improvements

### ISSUE THREAD

**Issue by vedmant** [ezl/dailyidea.com#936]
Following https://github.com/ezl/dailyidea.com/issues/485

- [x] Fix issue with placeholder when only image added
- [ ] Support images and attachments added by trix ?
- [ ] Support for multiple files selection from attachment button ?
- [ ] Support copy-paste for images / files ?

**Comment by vedmant** [comment]
@ezl Few questions, is it important to make new editor support editing older ideas? Specifically this is images and attachments added by trix, I'll need to create custom prosemirror nodes for them.

**Comment by ezl** [comment]
@vedmant will the older images still be DISPLAYED in the ideas, even if the new editor can't access or edit it?

**Comment by vedmant** [comment]
@ezl Yes, ideas are ok, only editor is not reading that images, so if to edit older idea it renders image from trix this way https://prnt.sc/10t7mhz . It's not that hard to add support for trix images, maybe an hour of work.

**Comment by ezl** [comment]
@vedmant no need to add support for previous images still. Very small corner case, and once we change, it will end up being legacy code

For the case of users needing to edit old ones, they can still just download it since it's being displayed then reupload it using the new editor.

Thanks for being thoughtful and thinking about this though.
