### ISSUE TITLE
Update to idea focus view and comment placement

### ISSUE THREAD

**Issue by Watson-B** [ezl/dailyidea.com#949]
Discussed the changes to the placement of comments and the full screen idea view with @ezl and we settled on the following. For reference, there is a basic click-through [here](https://www.figma.com/proto/TQDE3BG42EBzwupE1FLAtK/full-idea-comment?node-id=8%3A0&viewport=673%2C319%2C0.1138617992401123&scaling=min-zoom&page-id=0%3A1). In the default swipe view, we will remove comments and the idea will not scroll. When a user taps on the idea, it will open into the full page idea, originally referenced in #875 The user can then scroll through the idea, at the bottom of which there is a prompt to "View all X comments" or "Start the conversation" if there are no comments. ![updated-full-page-comment](https://user-images.githubusercontent.com/65913664/112573049-bc69bb00-8da8-11eb-826d-81cc6de5d3c1.gif)

**Comment by ikosovec** [comment]
@vedmant you can start implementing this. @Watson-B will think of a microtransition animation between fullscreen and popup modes and will add it additionally. The microtransition shouldn't block the functional part of this, right?

**Comment by vedmant** [comment]
@ezl  Ok, so as I understand this will be a full screen dialog, it will still stay on the same page without url change?

@Watson-B What about clicking on comments button on explore screen, will it just show dialog on top?

**Comment by ezl** [comment]
@vedmant:

(A) isn't it posisble to have the modal with a url change?
(B) what would be the pros/cons of doing so?
(C) will there be a url change between viewing the idea in swiping mode (currently has the direct link to the idea) vs clicking into it (where it has `<- back` in the upper left and it is not swipeable anymore?)

**Comment by vedmant** [comment]
@ezl 

The question was more not about changing URL but if it should stay on the same page or go to separate one. Having separate page means faster loading when it's opened from url (it will not load all the swiper functionality and next ideas to swipe). This however means some separate url for full idea page so we may have two sets of urls for the same idea then, something like `https://www.dailyidea.com/explore/4hvfl3/idea-for-daily-idea` for swiper and `https://www.dailyidea.com/i/4hvfl3/idea-for-daily-idea` for full idea page.

(A) Sure it's possible, the easiest is to stay on explore page but append a query string something `https://www.dailyidea.com/i/4hvfl3/idea-for-daily-idea?full` so if to open this url it will open full idea dialog on top of opened idea currently in swiper.

(B) Having different url means user can open page with opened full idea dialog. Without this it will open normal swiper mode. No really cons if to add a query string like `?full`, having separate url like /explore/... and /i/... can have come cons, like duplicate urls with same content. Generally from logical view cleaner will be to have separate urls for explorer and individual idea, event to not change urls in the explorer, instead have something like /explorer/new /explorer/top and so on.

(C) so that's the question I ask, ether to navigate to different page or to stay on explorer page and just add `?full` for opening full idea dialog.

**Comment by ezl** [comment]
Ah I see. I'm not 100% sure I'm understanding, so I will try to respond, and if I say anything that doesn't make complete sense, please point it out.

1. I think the way you are describing it, `https://www.dailyidea.com/i/4hvfl3/idea-for-daily-idea?full` and `https://www.dailyidea.com/i/4hvfl3/idea-for-daily-idea` are considered "same URL" but one has query string, is that correct? This is also the same thing as "staying on the same page" even if we are appending a query string argument.
2. having "same url" is *easier* to implement
3. having "same url" means less code to maintain (i.e. not "2 sets of urls for the same idea") and is easier for us to reason about
4. one potential negative is we won't be able to go link to a "full page"("opened full idea dialog") view of the idea if we want to.

If I've understood the above correctly without errors, then I think we should use the same url with query string.

I do not think it is a benefit to be able to go directly to a full page idea view. In fact, I PREFER for shared urls to go to the idea in swiper view, so people who receive a shared idea will then be able to start swiping.

However, I do NOT understand this quote from your last comment:

> Generally from logical view cleaner will be to have separate urls for explorer and individual idea, event to not change urls in the explorer, instead have something like /explorer/new /explorer/top and so on.

**Comment by vedmant** [comment]
@ezl Ok, then I'll proceed with full size dialog on top of explorer, and use query string `?full` to open it on page load.

> However, I do NOT understand this quote from your last comment:

I meant that for me it looks cleaner to have separate page for single idea as well as it's more optimized. But generally it's not a big difference.

**Comment by ezl** [comment]
got it, ok.

for now, let's do the dialog on top of explorer. I THINK I'm understanding it, at least enough for us to proceed.

I'll know for sure once we have it in production, and I think that will be the best way to see at this point.

**Comment by vedmant** [comment]
@Watson-B Also let me know how it will look on mobile.

**Comment by vedmant** [comment]
- [ ] New expand style and animation
- [ ] Remove comments section
- [ ] Set / remove `full` query string in the URL
- [ ] When page opened check for `full` query string
- [ ] New modal for comments
- [ ] How will expanded state look on mobile?
- [ ] Expanded states on user ideas pages?

**Comment by vedmant** [comment]
@ezl @ikosovec Ok, I'm merging this issue, for mobile and my ideas pages I just used simplest way to keep it look appropriate. I kept lightbox in my ideas pages, maybe it has to be done similar to explore page now. 

I also think it will require some refactoring now, since we removed in-place editing, comments and lightbox, there are now not really needed components hanging.

**Comment by vedmant** [comment]
@ezl @ikosovec  I'm merging this task, for mobile and my ideas pages I kept the simplest to implement option, no sure if this is what designer intended however as there were no mobile example.

I think it needs some refactoring since we removed in-place editing, comments and lightbox there are now not needed components and some extra data / events passed around due to this.

**Comment by ikosovec** [comment]
@Watson-B can you also please make a design review on this to see whether this is fine from your perspective?

**Comment by Watson-B** [comment]
@vedmant I took a pass at the mobile design, and @ikosovec and @ezl I'd love some input here.
The first two are inspired by how Instagram is handling the focus on a post into the comments, ditching the bottom nav and moving the interaction points (emojis + comment input field) for comments down into that space.
**Option 1**
<img width="360" alt="full idea 1" src="https://user-images.githubusercontent.com/65913664/114321769-5338b600-9ad1-11eb-9dbb-a88b185d7cc4.png">
**Option 2**
<img width="320" alt="full idea 2" src="https://user-images.githubusercontent.com/65913664/114321770-53d14c80-9ad1-11eb-9ba9-8cf1cf12c24b.png">

The second two keep the bottom nav, and then just alternate what's fixed at the top. 
**Option 3**
<img width="320" alt="full idea 4" src="https://user-images.githubusercontent.com/65913664/114321777-5f247800-9ad1-11eb-8bfe-fc6565946f75.png"> 
**Option 4**
<img width="320" alt="full idea 3" src="https://user-images.githubusercontent.com/65913664/114321775-5e8be180-9ad1-11eb-8823-3b1a524a5fb0.png">

Personal preference, I think option 2 maximizes the amount of the idea on the screen, and keeps the potential interactions down in the comfortable thumb zone.

**Comment by vedmant** [comment]
@Watson-B How it will animate from the card we have now:

<img width="462" alt="Test - Daily Idea 2021-04-12 16-28-49" src="https://user-images.githubusercontent.com/5052406/114402112-31603180-9bac-11eb-94b1-56ed062706cd.png">

to the example you added above?
Right now it just scales, but layout is different on your example, can you show example of both, mobile swiper view, expanded card and rules for expanding animation.

**Comment by ezl** [comment]
@vedmant @Watson-B - I vote to move this into a separate, future potential ticket.

I believe the original ticket scope is already completed and a significant improvement. 

@vedmant if you agree, feel free to close this ticket.

@Watson-B I'll add this discussion to a weekly sync for us, if that's ok.

**Comment by vedmant** [comment]
Sure, closing this then.
