### ISSUE TITLE
I get locked in by a "welcome back" dialogue

### ISSUE THREAD

**Issue by ikosovec** [ezl/dailyidea.com#967]
Steps to reproduce:
- I arrive at beta.dailyidea.com as a non-logged-in user
- I click on "Post"
- A "welcome back" dialogue opens up, as seen here: 
![image](https://user-images.githubusercontent.com/16639403/114076712-48024200-98a7-11eb-801f-2e1167c14ee0.png)
- I can't exit the dialogue in any way

Expected:
- I need an unblocking action as a user. I'm stuck

Any idea what we should do here @Watson-B? 
Keep in mind that as a non-logged-in user when you click the "Post" button you're already presented with a "create idea" in the background. I guess clicking outside of the dialogue should take you back to the previous page? From the other hand, that might also be a very weird behaviour.

**Comment by Watson-B** [comment]
Is this the first modal that opened for you, or did you enter your email and then go to this screen?


![image](https://user-images.githubusercontent.com/65913664/114317416-d7cd0980-9abc-11eb-8bd4-15128bb5e7ae.png)


In the original designs, the cancel text was updated to "Go Back' for the first step, and then there was an 'x' on the second step, the modal you posted (and also a different illustration, this is the one for liking a post), which when clicked should take the user back to the previous screen. 

![image](https://user-images.githubusercontent.com/65913664/114317466-15ca2d80-9abd-11eb-9df1-fb869848e065.png)


The more I think about it though, an 'x' that takes the user back still is not an ideal interaction and might be a weird behavior to users. Thoughts on replacing the 'x' with a back arrow in instances where if the user chooses not to log in, and wants to close the modal, the expected outcome will be clearer?

![image](https://user-images.githubusercontent.com/65913664/114317568-8cffc180-9abd-11eb-97cb-4f703fa06b0e.png)

**Comment by ikosovec** [comment]
I think the "Back" suggestion is good.
Moving it up on the dev priority list.

**Comment by vedmant** [comment]
@Watson-B So what back button will do, navigate to previous page, where user came from? 

I also see on design dialogs don't have backdrops, while they have them on modal. I generally can disable it so user can click on menu for example. In this case modal can't be closed on backdrop click, also I'll need to hide idea form then.

**Comment by Watson-B** [comment]
@vedmant yes, it should take them back to the page they came from. If there will be issues with that, then it should take them back to 'explore' since as an unauthorized user that is the only section of the site they can use.

In regards to the backdrop, @ezl raised a good point when we were doing the redesign; that since unauthorized users will not be able to access "Post" or "My Ideas" until they log in, that it doesn't make sense to show them the Post form behind the modal. So rather than treating the card as a modal, I was treating it as a card on the page, so that they user would still be able to click 'explore' to navigate away.

**Comment by vedmant** [comment]
Ok, I added back button as in example
